# Generated by Django 5.2.4 on 2025-07-23 09:39

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_book"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(
                null=True, upload_to=core.models.book_image_file_path
            ),
        ),
    ]
